/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'projectDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getRequestByIndex' : IDL.Func([IDL.Nat], [QuoteRequest], ['query']),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getRequestByIndex' : IDL.Func([IDL.Nat], [QuoteRequest], ['query']),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };